tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: logo
            field:
              max_files: 1
              min_files: 1
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: Logo
              icon: assets
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: pitch
            field:
              input_type: text
              antlers: false
              type: text
              display: Pitch
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          -
            handle: link_title
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Link Title'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          -
            handle: link
            field:
              input_type: text
              antlers: false
              type: text
              display: Link
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
  sidebar:
    display: Sidebar
    sections:
      - {  }
title: Product
